// apps/web-react/src/components/EmptyState/EmptyState.tsx
import "./EmptyState.css";

export function EmptyState() {
  return (
    <section className="empty-state">
      <h2>Ready to investigate</h2>
      <p>
        Paste a failing test log, add optional context, choose the framework,
        and get structured debugging guidance powered by AI.
      </p>
    </section>
  );
}

// apps/web/src/components/EmptyState.vue
<template>
  <section class="empty-state">
    <h2>Ready to investigate</h2>
    <p>
      Paste a failing test log, add optional context, choose the framework, and get
      structured debugging guidance powered by AI.
    </p>
  </section>
</template>

<style scoped>
.empty-state {
  max-width: 720px;
  margin: 2rem auto 0;
  padding: 2rem;
  border: 1px dashed #d0d5dd;
  border-radius: 12px;
  background: #fcfcfd;
  text-align: center;
}

.empty-state h2 {
  margin: 0 0 0.75rem;
  font-size: 1.25rem;
}

.empty-state p {
  margin: 0;
  color: #667085;
  line-height: 1.6;
}
</style>
